name: Controlla Concorsi

on:
  schedule:
    - cron: '0 21 * * 2'  # martedì alle 21:00 UTC
    - cron: '0 21 * * 5'  # venerdì alle 21:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run script
        env:
          EMAIL_MITTENTE: ${{ secrets.EMAIL_MITTENTE }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
        run: python concorsi.py
